<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ShopsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('shops')->delete();
        
        \DB::table('shops')->insert(array (
            0 => 
            array (
                'address' => '銀座１−１−１',
                'banner_url' => NULL,
                'building' => '銀座ビル２F',
                'category' => NULL,
                'city' => '中央区',
                'created_at' => '2023-01-31 11:52:49',
                'deleted_at' => NULL,
                'distributor' => '株式会社天のめぐみ',
                'id' => 1,
                'image_id' => 48,
                'industry_id' => 1234567890,
                'introduction' => 'ファッションの美しさをすべての人が利用できるようにすることを目的とした、ファッションとライフシーンの電子小売業者です。 在庫の無駄を減らし、手頃な価格の製品を提供できるようにします。',
                'is_same_officer' => 1,
                'mail' => 'info@qest.mall',
                'officer_name' => '山田太郎',
                'officer_name_kana' => NULL,
                'personal_info_officer_name' => NULL,
                'personal_info_officer_name_kana' => NULL,
                'prefecture_id' => 14,
                'shop_name' => '天のめぐみ',
                'shop_name_kana' => 'テンノメグミ',
                'shop_tt_code' => 'TT12345678',
                'tel' => '03-0000-0000',
                'updated_at' => '2023-01-31 11:52:49',
                'visibility_status' => 1,
                'zip_code' => 1150001,
            ),
            1 => 
            array (
                'address' => NULL,
                'banner_url' => NULL,
                'building' => NULL,
                'category' => NULL,
                'city' => NULL,
                'created_at' => '2023-01-31 11:52:49',
                'deleted_at' => NULL,
                'distributor' => NULL,
                'id' => 2,
                'image_id' => 45,
                'industry_id' => NULL,
                'introduction' => 'ファッションの美しさをすべての人が利用できるようにすることを目的とした、ファッションとライフシーンの電子小売業者です。 在庫の無駄を減らし、手頃な価格の製品を提供できるようにします。',
                'is_same_officer' => 0,
                'mail' => NULL,
                'officer_name' => NULL,
                'officer_name_kana' => NULL,
                'personal_info_officer_name' => NULL,
                'personal_info_officer_name_kana' => NULL,
                'prefecture_id' => NULL,
                'shop_name' => 'mill mill',
                'shop_name_kana' => 'ミルミル',
                'shop_tt_code' => 'TT87654321',
                'tel' => NULL,
                'updated_at' => '2023-01-31 11:52:49',
                'visibility_status' => 1,
                'zip_code' => NULL,
            ),
            2 => 
            array (
                'address' => NULL,
                'banner_url' => NULL,
                'building' => NULL,
                'category' => NULL,
                'city' => NULL,
                'created_at' => '2023-01-31 11:52:49',
                'deleted_at' => NULL,
                'distributor' => NULL,
                'id' => 3,
                'image_id' => 47,
                'industry_id' => NULL,
                'introduction' => 'ファッションの美しさをすべての人が利用できるようにすることを目的とした、ファッションとライフシーンの電子小売業者です。 在庫の無駄を減らし、手頃な価格の製品を提供できるようにします。',
                'is_same_officer' => 0,
                'mail' => NULL,
                'officer_name' => NULL,
                'officer_name_kana' => NULL,
                'personal_info_officer_name' => NULL,
                'personal_info_officer_name_kana' => NULL,
                'prefecture_id' => NULL,
                'shop_name' => '& Life.',
                'shop_name_kana' => 'アンドライフ',
                'shop_tt_code' => NULL,
                'tel' => NULL,
                'updated_at' => '2023-01-31 11:52:49',
                'visibility_status' => 1,
                'zip_code' => NULL,
            ),
            3 => 
            array (
                'address' => NULL,
                'banner_url' => '/images/shop_banner/shop_libre_banner.png',
                'building' => NULL,
                'category' => NULL,
                'city' => NULL,
                'created_at' => '2023-01-31 11:52:49',
                'deleted_at' => NULL,
                'distributor' => NULL,
                'id' => 4,
                'image_id' => 44,
                'industry_id' => NULL,
                'introduction' => 'ファッションの美しさをすべての人が利用できるようにすることを目的とした、ファッションとライフシーンの電子小売業者です。 在庫の無駄を減らし、手頃な価格の製品を提供できるようにします。ファッションの美しさをすべての人が利用できるようにすることを目的とした、ファッションとライフシーンの電子小売業者です。 在庫の無駄を減らし、手頃な価格の製品を提供できるようにします。ファッションの美しさをすべての人が利用できるようにすることを目的とした、ファッションとライフシーンの電子小売業者です。 在庫の無駄を減らし、手頃な価格の製品を提供できるようにします。',
                'is_same_officer' => 0,
                'mail' => NULL,
                'officer_name' => NULL,
                'officer_name_kana' => NULL,
                'personal_info_officer_name' => NULL,
                'personal_info_officer_name_kana' => NULL,
                'prefecture_id' => NULL,
                'shop_name' => 'LIBRE',
                'shop_name_kana' => 'リブレ',
                'shop_tt_code' => NULL,
                'tel' => NULL,
                'updated_at' => '2023-01-31 11:52:49',
                'visibility_status' => 1,
                'zip_code' => NULL,
            ),
            4 => 
            array (
                'address' => NULL,
                'banner_url' => NULL,
                'building' => NULL,
                'category' => NULL,
                'city' => NULL,
                'created_at' => '2023-01-31 11:52:49',
                'deleted_at' => NULL,
                'distributor' => NULL,
                'id' => 5,
                'image_id' => 46,
                'industry_id' => NULL,
                'introduction' => 'ファッションの美しさをすべての人が利用できるようにすることを目的とした、ファッションとライフシーンの電子小売業者です。 在庫の無駄を減らし、手頃な価格の製品を提供できるようにします。',
                'is_same_officer' => 0,
                'mail' => NULL,
                'officer_name' => NULL,
                'officer_name_kana' => NULL,
                'personal_info_officer_name' => NULL,
                'personal_info_officer_name_kana' => NULL,
                'prefecture_id' => NULL,
                'shop_name' => 'BABY BABY',
                'shop_name_kana' => 'ベイビーベイビー',
                'shop_tt_code' => NULL,
                'tel' => NULL,
                'updated_at' => '2023-01-31 11:52:49',
                'visibility_status' => 1,
                'zip_code' => NULL,
            ),
            5 => 
            array (
                'address' => NULL,
                'banner_url' => NULL,
                'building' => NULL,
                'category' => NULL,
                'city' => NULL,
                'created_at' => '2023-01-31 11:52:49',
                'deleted_at' => NULL,
                'distributor' => NULL,
                'id' => 6,
                'image_id' => 48,
                'industry_id' => NULL,
                'introduction' => 'ファッションの美しさをすべての人が利用できるようにすることを目的とした、ファッションとライフシーンの電子小売業者です。 在庫の無駄を減らし、手頃な価格の製品を提供できるようにします。',
                'is_same_officer' => 0,
                'mail' => NULL,
                'officer_name' => NULL,
                'officer_name_kana' => NULL,
                'personal_info_officer_name' => NULL,
                'personal_info_officer_name_kana' => NULL,
                'prefecture_id' => NULL,
                'shop_name' => '天のめぐみ',
                'shop_name_kana' => 'テンノメグミ',
                'shop_tt_code' => 'TT12345678',
                'tel' => NULL,
                'updated_at' => '2023-01-31 11:52:49',
                'visibility_status' => 1,
                'zip_code' => NULL,
            ),
            6 => 
            array (
                'address' => NULL,
                'banner_url' => NULL,
                'building' => NULL,
                'category' => NULL,
                'city' => NULL,
                'created_at' => '2023-01-31 11:52:49',
                'deleted_at' => NULL,
                'distributor' => NULL,
                'id' => 7,
                'image_id' => 45,
                'industry_id' => NULL,
                'introduction' => 'ファッションの美しさをすべての人が利用できるようにすることを目的とした、ファッションとライフシーンの電子小売業者です。 在庫の無駄を減らし、手頃な価格の製品を提供できるようにします。',
                'is_same_officer' => 0,
                'mail' => NULL,
                'officer_name' => NULL,
                'officer_name_kana' => NULL,
                'personal_info_officer_name' => NULL,
                'personal_info_officer_name_kana' => NULL,
                'prefecture_id' => NULL,
                'shop_name' => 'mill mill',
                'shop_name_kana' => 'ミルミル',
                'shop_tt_code' => 'TT87654321',
                'tel' => NULL,
                'updated_at' => '2023-01-31 11:52:49',
                'visibility_status' => 1,
                'zip_code' => NULL,
            ),
            7 => 
            array (
                'address' => NULL,
                'banner_url' => NULL,
                'building' => NULL,
                'category' => NULL,
                'city' => NULL,
                'created_at' => '2023-01-31 11:52:49',
                'deleted_at' => NULL,
                'distributor' => NULL,
                'id' => 8,
                'image_id' => 47,
                'industry_id' => NULL,
                'introduction' => 'ファッションの美しさをすべての人が利用できるようにすることを目的とした、ファッションとライフシーンの電子小売業者です。 在庫の無駄を減らし、手頃な価格の製品を提供できるようにします。',
                'is_same_officer' => 0,
                'mail' => NULL,
                'officer_name' => NULL,
                'officer_name_kana' => NULL,
                'personal_info_officer_name' => NULL,
                'personal_info_officer_name_kana' => NULL,
                'prefecture_id' => NULL,
                'shop_name' => '& Life.',
                'shop_name_kana' => 'アンドライフ',
                'shop_tt_code' => NULL,
                'tel' => NULL,
                'updated_at' => '2023-01-31 11:52:49',
                'visibility_status' => 1,
                'zip_code' => NULL,
            ),
            8 => 
            array (
                'address' => NULL,
                'banner_url' => '/images/shop_banner/shop_libre_banner.png',
                'building' => NULL,
                'category' => NULL,
                'city' => NULL,
                'created_at' => '2023-01-31 11:52:49',
                'deleted_at' => NULL,
                'distributor' => NULL,
                'id' => 9,
                'image_id' => 44,
                'industry_id' => NULL,
                'introduction' => 'ファッションの美しさをすべての人が利用できるようにすることを目的とした、',
                'is_same_officer' => 0,
                'mail' => NULL,
                'officer_name' => NULL,
                'officer_name_kana' => NULL,
                'personal_info_officer_name' => NULL,
                'personal_info_officer_name_kana' => NULL,
                'prefecture_id' => NULL,
                'shop_name' => 'LIBRE',
                'shop_name_kana' => 'リブレ',
                'shop_tt_code' => NULL,
                'tel' => NULL,
                'updated_at' => '2023-01-31 11:52:49',
                'visibility_status' => 1,
                'zip_code' => NULL,
            ),
            9 => 
            array (
                'address' => NULL,
                'banner_url' => NULL,
                'building' => NULL,
                'category' => NULL,
                'city' => NULL,
                'created_at' => '2023-01-31 11:52:49',
                'deleted_at' => NULL,
                'distributor' => NULL,
                'id' => 10,
                'image_id' => 46,
                'industry_id' => NULL,
                'introduction' => 'ファッションの美しさをすべての人が利用できるようにすることを目的とした、ファッションとライフシーンの電子小売業者です。 在庫の無駄を減らし、手頃な価格の製品を提供できるようにします。',
                'is_same_officer' => 0,
                'mail' => NULL,
                'officer_name' => NULL,
                'officer_name_kana' => NULL,
                'personal_info_officer_name' => NULL,
                'personal_info_officer_name_kana' => NULL,
                'prefecture_id' => NULL,
                'shop_name' => 'BABY BABY',
                'shop_name_kana' => 'ベイビーベイビー',
                'shop_tt_code' => NULL,
                'tel' => NULL,
                'updated_at' => '2023-01-31 11:52:49',
                'visibility_status' => 1,
                'zip_code' => NULL,
            ),
            10 => 
            array (
                'address' => NULL,
                'banner_url' => NULL,
                'building' => NULL,
                'category' => NULL,
                'city' => NULL,
                'created_at' => '2023-01-31 11:52:49',
                'deleted_at' => NULL,
                'distributor' => NULL,
                'id' => 11,
                'image_id' => 48,
                'industry_id' => NULL,
                'introduction' => NULL,
                'is_same_officer' => 0,
                'mail' => NULL,
                'officer_name' => NULL,
                'officer_name_kana' => NULL,
                'personal_info_officer_name' => NULL,
                'personal_info_officer_name_kana' => NULL,
                'prefecture_id' => NULL,
                'shop_name' => '天のめぐみ',
                'shop_name_kana' => 'テンノメグミ',
                'shop_tt_code' => 'TT12345678',
                'tel' => NULL,
                'updated_at' => '2023-01-31 11:52:49',
                'visibility_status' => 1,
                'zip_code' => NULL,
            ),
        ));
        
        
    }
}